# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: sitecamalecode
services:
  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
